services:
  vosk:
    image: ghcr.io/frauhottelmann/wyoming-vosk-standalone:1.5.0
    container_name: vosk
    environment:
      - CORRECT_SENTENCES=0.0
      - PRELOAD_LANGUAGE=en
      - DEBUG_LOGGING=TRUE
      - LIMIT_SENTENCES=TRUE
      - ALLOW_UNKNOWN=False
    volumes:
      - ./vosk/data:/data
      - ./vosk/sentences:/share/vosk/sentences
      - ./vosk/models:/share/vosk/models
    ports:
      - 10300:10300
    restart: unless-stopped
